service: polyfill

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  region: us-west-2

package:
  exclude:
  - server.js
  - coverage/
  - test/

functions:
  minified:
    handler: handler.mininify
    events:
    - http:
        path: polyfill.min.js
        method: GET
        cors:
          origin: '*'
          maxAge: 86400
          allowCredentials: true

  normal:
    handler: handler.normal
    events:
    - http:
        path: polyfill.js
        method: GET
        cors:
          origin: '*'
          maxAge: 86400
          allowCredentials: true
